version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-symfony-app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"

  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_DATABASE: practicasymfonybdd
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    ports:
      - "3306:3306"
